spring.datasource.url=jdbc:mysql://database:3306/flow_manager
spring.datasource.username=root
spring.datasource.password=rootpassword

# cors.allowed-origins=http://localhost:80
cors.allowed-origins=*