spring.datasource.url=jdbc:mysql://mysql:3306/flow_manager?serverTimezone=UTC
# spring.datasource.url=jdbc:mysql://mysql:3306/flow_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
# spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
spring.datasource.username=root
spring.datasource.password=rootpassword

# cors.allowed-origins=http://localhost:80
cors.allowed-origins=*

spring.servlet.encoding.enabled=true
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.messages.encoding=UTF-8
