-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 02:03:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flow_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flow_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flow_manager` DEFAULT CHARACTER SET utf8 ;
USE `flow_manager` ;

-- -----------------------------------------------------
-- Table `flow_manager`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `perfil` ENUM('CLIENTE', 'PROFISSIONAL', 'ADMIN') NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 0,
  `nome` VARCHAR(100) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`profissional` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profissional_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_profissional_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `flow_manager`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`horario_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`horario_atendimento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `profissional_id` BIGINT NOT NULL,
  `dia_semana` ENUM('SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horario_atendimento_profissional_idx` (`profissional_id` ASC) VISIBLE,
  CONSTRAINT `fk_horario_atendimento_profissional`
    FOREIGN KEY (`profissional_id`)
    REFERENCES `flow_manager`.`profissional` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`cliente` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `flow_manager`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`servico` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `duracao` INT NULL COMMENT '`duracao` INT NOT NULL COMMENT \'Duração em minutos\',',
  `valor` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`agendamento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cliente_id` BIGINT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `status` ENUM('AGENDADO', 'CANCELADO', 'CONCLUIDO', 'REAGENDADO') NOT NULL,
  `observacao` TEXT NULL,
  `desconto` DECIMAL(10,2) NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamento_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `flow_manager`.`cliente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`profissional_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`profissional_servico` (
  `profissional_id` BIGINT NOT NULL,
  `servico_id` BIGINT NOT NULL,
  PRIMARY KEY (`profissional_id`, `servico_id`),
  INDEX `fk_servico_has_profissional_profissional_idx` (`profissional_id` ASC) VISIBLE,
  INDEX `fk_servico_has_profissional_servico_idx` (`servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_servico_has_profissional_servico`
    FOREIGN KEY (`servico_id`)
    REFERENCES `flow_manager`.`servico` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_servico_has_profissional_profissional`
    FOREIGN KEY (`profissional_id`)
    REFERENCES `flow_manager`.`profissional` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`agendamento_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`agendamento_servico` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `agendamento_id` BIGINT NOT NULL,
  `profissional_id` BIGINT NOT NULL,
  `servico_id` BIGINT NOT NULL,
  INDEX `fk_agendamento_has_servico_agendamento1_idx` (`agendamento_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_agendamento_servico_agendamento_profissional_servico` (`agendamento_id` ASC, `profissional_id` ASC, `servico_id` ASC) INVISIBLE,
  INDEX `idx_agendamento_servico_profissional_servico` (`profissional_id` ASC, `servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_has_servico_agendamento`
    FOREIGN KEY (`agendamento_id`)
    REFERENCES `flow_manager`.`agendamento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_profissional`
    FOREIGN KEY (`profissional_id` , `servico_id`)
    REFERENCES `flow_manager`.`profissional_servico` (`profissional_id` , `servico_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`especialidade` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flow_manager`.`profissional_especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flow_manager`.`profissional_especialidade` (
  `profissional_id` BIGINT NOT NULL,
  `especialidade_id` BIGINT NOT NULL,
  INDEX `fk_profissional_especialidade_profissional1_idx` (`profissional_id` ASC) VISIBLE,
  INDEX `fk_profissional_especialidade_especialidade1_idx` (`especialidade_id` ASC) VISIBLE,
  PRIMARY KEY (`profissional_id`, `especialidade_id`),
  CONSTRAINT `fk_profissional_especialidade_profissional1`
    FOREIGN KEY (`profissional_id`)
    REFERENCES `flow_manager`.`profissional` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_profissional_especialidade_especialidade1`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `flow_manager`.`especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
