-- -- Tabela Especialidade
-- CREATE TABLE IF NOT EXISTS `flow_manager`.`especialidade` (
--   `id` BIGINT NOT NULL AUTO_INCREMENT,
--   `nome` VARCHAR(100) NOT NULL,
--   `descricao` VARCHAR(255) NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE INDEX `uk_especialidade_nome` (`nome` ASC) VISIBLE
-- ) ENGINE = InnoDB;

-- -- Tabela Profissional_Especialidade (Junction Table)
-- CREATE TABLE IF NOT EXISTS `flow_manager`.`profissional_especialidade` (
--   `id` BIGINT NOT NULL AUTO_INCREMENT,
--   `profissional_id` BIGINT NOT NULL,
--   `especialidade_id` BIGINT NOT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE INDEX `uk_prof_espec` (`profissional_id` ASC, `especialidade_id` ASC) VISIBLE,
--   INDEX `fk_profissional_especialidade_especialidade_idx` (`especialidade_id` ASC) VISIBLE,
--   CONSTRAINT `fk_profissional_especialidade_profissional`
--     FOREIGN KEY (`profissional_id`)
--     REFERENCES `flow_manager`.`profissional` (`id`)
--     ON DELETE CASCADE
--     ON UPDATE CASCADE,
--   CONSTRAINT `fk_profissional_especialidade_especialidade`
--     FOREIGN KEY (`especialidade_id`)
--     REFERENCES `flow_manager`.`especialidade` (`id`)
--     ON DELETE CASCADE
--     ON UPDATE CASCADE
-- ) ENGINE = InnoDB;
